export const personalRadarCopy = {
  zh: {
    brand: '留美路径雷达',
    myRadar: '我的雷达',
    policies: '政策',
    cptSchools: 'CPT 学校',
    updates: '更新记录',
    stats: '访问统计',
    top: '回到顶部 ↑',
    nav: '页面导航',
    language: '切换网站语言',
    eyebrow: '我的雷达 · 从你的状态出发',
    intro: '把与你有关的变化，放在视野中心。',
    current: '我现在',
    goal: '下一步计划',
    none: '还没决定',
    title: '你的政策视野',
    subtitle: '方位看阶段 · 距离看时间',
    showAll: '显示其他政策',
    head: (current: string, goal: string | null) =>
      goal
        ? `你在 ${current}，下一站 ${goal}。`
        : `你在 ${current}，看清眼前的变化。`,
    summary: (now: number, next: number) =>
      `${now} 项当前相关 · ${next} 项影响下一步`,
    drag: '拖动「起」「终」，调整关注路径',
    now: '当前相关',
    next: '下一步',
    all: '全部相关',
    list: '与你有关的政策',
    order: '按影响程度排序',
    empty: '这个阶段暂时没有收录的政策。',
    inForce: '已在执行',
    pending: '尚未生效',
    severe: '严重',
    lower: '较低',
    selected: '正在查看',
    read: '查看政策与来源',
    impact: '影响程度',
    source: '评分来源',
    status: '实施状态',
    timing: '影响时间',
    relevance: '与你的关系',
    community: '社区真实评分',
    ai: 'AI 影响预估',
    low: '低置信度',
    veryLow: '极低置信度',
    count: (n: number) => `${n} 份真实评分`,
    aiCount: (n: number) => `${n}/10 份真实评分 · AI 分数不计入社区均分`,
    unavailable: '社区评分暂时不可用',
    unavailableNote: '暂时显示 AI 估计；未把读取失败计作零份评分。',
    currentMatch: '匹配当前身份',
    nextMatch: '位于接下来的路径',
    outside: '在所选路径之外，显示供参考。',
    basis: '估计依据与适用条件',
    scoreBasis: '影响估计',
    timingBasis: '时间估计',
    baseline: '估计基准日',
    conditional: '对受适用条件影响者的后果强度；不代表个人风险或规则发生概率。',
    timeNote:
      '点位按时间区间归类，并非精确倒计时；AI 估计可能提前、延后或不落地。做个人决定前，请复核原始文件并咨询专业人士。',
    privacy: '身份与计划仅保存在当前浏览器。',
    close: '关闭政策浮窗',
    note: '不足 10 份真实评分时显示独立的 AI 影响预估。满 10 份后使用真实均分。',
  },
  en: {
    brand: 'Stay Path Radar',
    myRadar: 'My radar',
    policies: 'Policies',
    cptSchools: 'CPT Schools',
    updates: 'Updates',
    stats: 'Traffic',
    top: 'Back to top ↑',
    nav: 'Page navigation',
    language: 'Switch site language',
    eyebrow: 'My radar · Start from where you are',
    intro: 'Keep the changes that matter to you in view.',
    current: 'Where I am',
    goal: 'My next step',
    none: 'Not decided',
    title: 'Your policy radar',
    subtitle: 'Direction is stage · Distance is timing',
    showAll: 'Show other policies',
    head: (current: string, goal: string | null) =>
      goal ? `${current} now. ${goal} next.` : `${current}: see what is ahead.`,
    summary: (now: number, next: number) =>
      `${now} relevant now · ${next} on your next steps`,
    drag: 'Drag S (start) and E (end) to adjust your path',
    now: 'Current stage',
    next: 'Next steps',
    all: 'All relevant',
    list: 'Policies on your path',
    order: 'By impact',
    empty: 'No tracked policies in this stage yet.',
    inForce: 'In force',
    pending: 'Not yet in force',
    severe: 'Severe',
    lower: 'Lower',
    selected: 'Selected policy',
    read: 'Read policy & sources',
    impact: 'Impact',
    source: 'Source',
    status: 'Status',
    timing: 'Timing',
    relevance: 'Relevance',
    community: 'Genuine community ratings',
    ai: 'AI impact estimate',
    low: 'Low confidence',
    veryLow: 'Very low confidence',
    count: (n: number) => `${n} genuine ${n === 1 ? 'rating' : 'ratings'}`,
    aiCount: (n: number) =>
      `${n}/10 genuine ratings · AI excluded from community average`,
    unavailable: 'Community ratings temporarily unavailable',
    unavailableNote:
      'Showing AI estimates for now; a failed request is not counted as zero votes.',
    currentMatch: 'Matches your current stage',
    nextMatch: 'On your upcoming path',
    outside: 'Outside your selected path; shown for context.',
    basis: 'Estimate basis & applicability',
    scoreBasis: 'Impact estimate',
    timingBasis: 'Timing estimate',
    baseline: 'Estimate baseline',
    conditional:
      'Consequence severity for people covered by the conditions; not personal risk or the probability of a rule taking effect.',
    timeNote:
      'Positions represent time ranges, not precise countdowns. AI estimates may arrive earlier, later, or never take effect. Verify primary sources and obtain professional advice before making individual decisions.',
    privacy: 'Your status and plan are saved only in this browser.',
    close: 'Close policy popup',
    note: 'Below 10 genuine ratings, a separate AI estimate is shown. At 10 ratings, the genuine average takes priority.',
  },
};
